### ISSUE TITLE
Add a Thanks Textarea / Caption

### ISSUE THREAD

**Issue by ranbureand** [alpacaaa/dude#10]
Se ho già accordato l’accesso a Github, la seguente caption “Hey. Read-only access to Github is needed.” non dovrebbe essere più visibile una volta che ho espanso la textarea:

![dude_textarea_caption_00](https://cloud.githubusercontent.com/assets/1890508/6422286/7de83f6c-bedf-11e4-842c-f9298262e65e.jpg)

Potremmo rimpiazzarla direttamente con quella che appare immediatamente se l’utente inizia a scrivere, ovvero: “Pssst. Markdown and Emoji are supported.”.

**Comment by alpacaaa** [comment]
Vero, lo sistemerò!
