### ISSUE TITLE
Add a Thanks Textarea / Character Counter

### ISSUE THREAD

**Issue by ranbureand** [alpacaaa/dude#11]
Quanto rognoso è limitare il numero di caratteri che un utente può inserire quando ringrazia?

Se non è rognoso a farsi, potremmo tenere la caption “Pssst. Markdown and Emoji are supported. ” e aggiungere semplicemente il numero di caratteri subito dopo, in modo affine al [Character Counter](http://www.google.com/design/spec/components/text-fields.html#text-fields-full-width-text-field) descritto nelle linee guida del Material Design di Google.

Inoltre, se optiamo per limitare il numero di caratteri, che tetto fissiamo?

**Comment by alpacaaa** [comment]
Il tetto non so quale potrebbe essere (direi che possiamo sforare il tweet). Metto il counter nei TODO.

**Comment by alpacaaa** [comment]
Ho settato il limite di caratteri a 320. Il counter è, in tutta la sua bruttezza, nel file [comment-form.hbs](https://github.com/alpacaaa/dude/blob/e26265598c7aa26ad64177fde6169796c813157f/client/app/templates/components/comment-form.hbs#L22) :D

**Comment by ranbureand** [comment]
Ho sistemato il character counter, ma non so come inserire del codice HTML in una stringa in .coffee:

https://github.com/alpacaaa/dude/blob/master/client/app/components/comment-form.coffee#L13

: /

**Comment by alpacaaa** [comment]
Quello che hai fatto è corretto, ma nel template devi usare la tripla graffa `{{{ var }}}` per indicare che vuoi renderizzare la variabile come HTML ;)

**Comment by ranbureand** [comment]
Ah-han! Fatto! Ma per caso è anche possibile far renderizzare la variabile come Markdown?

**Comment by alpacaaa** [comment]
No quello no! :camel:

**Comment by ranbureand** [comment]
Accidenti, peccato! :) Direi che allora questa grana la possiamo chiudere, giusto?

**Comment by alpacaaa** [comment]
Yep!
