### ISSUE TITLE
Thank / Image

### ISSUE THREAD

**Issue by ranbureand** [alpacaaa/dude#16]
![dude_thank_image_00](https://cloud.githubusercontent.com/assets/1890508/6422614/87cf1600-bee3-11e4-9252-ca3a9be444e6.png)

L’ho rotto….

Inoltre non sono convinto che il layout di un thank quando uno aggiunge una sola immagine regga… mumble mumble.

**Comment by alpacaaa** [comment]
Tieni a mente una cosa... Può essere che in realtà funzioni nella versione statica che hai sviluppato, ma qui si spacca perchè Ember aggiunge markup in più. Ti capiterà di vedere `div.ember-view` in giro e, per quanto abbia cercato di eliminare quelli che creavano palesemente danni, me ne potrebbero essere sfuggiti alcuni. Non so se sia questo il caso, darò un'occhio.

**Comment by ranbureand** [comment]
In teoria anche questo dovrebbe essere a posto!
