### ISSUE TITLE
Repositories without a Thank You

### ISSUE THREAD

**Issue by ranbureand** [alpacaaa/dude#17]
Ho notato che, se un utente cerca un ripostiglio, questo viene automaticamente aggiunto e compare nella lista dei rispostigli di Dude in Index e Index / Letter, anche nel caso in cui l’utente non abbia effettivamente aggiunto alcun ringraziamento.

È possibile far si che il ripostiglio venga effettivamente aggiunto alla lista solo nel caso in cui l’utente abbia aggiunto almeno un ringraziamento, così da evitare di popolare la lista con ripostigli “vuoti”?

**Comment by alpacaaa** [comment]
Si può fare, in effetti ha più senso, lo cambierò.

_Oddio ma repository è veramente ripostiglio?! Pensavo stessi giocando con l'assonanza delle due parole... ripostiglio è fantastico._

**Comment by ranbureand** [comment]
Hahaha! Tra le [alternative](http://www.wordreference.com/enit/repository) era la migliore traduzione!

**Comment by alpacaaa** [comment]
Questo dovrebbe essere apposto!
