### ISSUE TITLE
Quick reach your Github starred repositories

### ISSUE THREAD

**Issue by ranbureand** [alpacaaa/dude#2]
Pensavo: perché non inserire il link per raggiungere i propri ripostigli preferiti nella caption del search field?

![dude_github_00](https://cloud.githubusercontent.com/assets/1890508/6421961/4fb7fe5a-bedc-11e4-98e0-33fb1078908f.jpg)

In questo modo il layout della pagina risulta assai più compatto.

**Comment by alpacaaa** [comment]
Molto meglio, approvo!

**Comment by ranbureand** [comment]
Perfetto. Domani sistemo il CSS delle caption, così da allinearle a sinistra (ho anche visto che padding-left e padding-right sono sballati, correggo il tiro anche su quelli).

**Comment by alpacaaa** [comment]
Ma quindi mostreresti il link per raggiungere i repo starred nello stesso punto in cui eventualmente ci sarebbero gli errori del form di ricerca? Per il momento l'ho modificato con questa interpretazione, in `search-repo.hbs` c'è una roba strana che è `{{yield}}` – essenzialmente è il punto in cui viene renderizzato l'altro template `starred-repos.hbs`.

**Comment by ranbureand** [comment]
Sì. Mi sto rendendo conto che il layout di Dude allo stato in cui è adesso è alquanto frammentario (soprattutto a causa dei titoli .notation delle varie section) e risulta apparentemente complesso: per questo motivo cercherei di compattare le cose il più possibile, in modo che siano di più facile digestione.

Accedere ai ripostigli preferiti è concettualmente una shortcut del search field, per questo motivo lo combinerei con quest’ultimo.

Per essendo il link per garantire l’accesso nella caption del field, sarebbe immediatamente visibile e rimarrebbe tale fino a quando un utente non si trovi a scrivere un indirizzo sbagliato e provi a cercarlo, al che darei per assodato che non gli interessa accedere ai proprio repository preferiti e che il rimpiazzamento del link con il messaggio di errore non sia più di tanto un problema.

Tu che ne pensi?

**Comment by alpacaaa** [comment]
Sono perfettamente d'accordo, volevo solo capire se avevo interpretato correttamente :D
