### ISSUE TITLE
Comments permalink

### ISSUE THREAD

**Issue by alpacaaa** [alpacaaa/dude#21]
Al posto che l'hash nell'URL possiamo aggiungere un ulteriore parametro per indicare il commento selezionato `/r/author/repo/comment-id`. Secondo me è più figo così e poi sono abbastanza sicuro che l'hash creerebbe problemi ad Ember, ha senso come soluzione?

E poi ci serve uno stile da applicare al commento linkato!

**Comment by ranbureand** [comment]
Stile aggiunto!
