### ISSUE TITLE
White Background

### ISSUE THREAD

**Issue by ranbureand** [alpacaaa/dude#22]
Non sono ancora sicuro di codesto cambiamento, ma forse ci torna utile per semplificare la percezione del sito, ovvero navigazione tutto ciò che sta sul giallo, contenuto tutto quello sul bianco:

![dude_white_background_00](https://cloud.githubusercontent.com/assets/1890508/6492139/c6d0cd82-c2ba-11e4-8d86-f01032266cad.png)

Spassionatamente, che ne pensi?!?

**Comment by alpacaaa** [comment]
Si ci può stare! A me il giallo uniforme non da particolarmente fastidio, ma posso vedere i benefici di questo approccio.

**Comment by ranbureand** [comment]
Implementato: che ne pensi? A me sembra funzionar….

**Comment by alpacaaa** [comment]
Funza anche per me, mi piace anche come hai modificato i commenti.

**Comment by ranbureand** [comment]
;-)
