### ISSUE TITLE
Ember 1.11

### ISSUE THREAD

**Issue by alpacaaa** [alpacaaa/dude#23]
Ho appena aggiornato Ember alla 1.11, ci sono un paio di cose che ti riguardano.

1) Devi aggiornare le tue librerie. Dopo aver pullato, spostati nella cartella client (`cd client`) e lancia `bower update`
2) Ho dovuto eliminare alcuni containers dai template (tipo `ol.comments`) quindi non preoccuparti se non li vedi più nei file .hbs :D Comunque il markup renderizzato dal browser è rimasto lo stesso
3) Il primo commento ha la classe `is_first`

Non mi sembra ci siano bug in giro, nel caso non ne dovessimo trovare, chiudiamo questa issue nei prossimi giorni ;)

**Comment by ranbureand** [comment]
Credo sia filato tutto liscio, per cui chiudo questa issue!
