### ISSUE TITLE
Social Media Share

### ISSUE THREAD

**Issue by ranbureand** [alpacaaa/dude#27]
Inserire un’immagine che venga pigliata e visualizzata nel momento in cui qualcuno condivida il link su Facebook, Twitter, ….

**Comment by alpacaaa** [comment]
Nello specifico dovremmo aggiungere i meta tag previsti dall'[Open Graph Protocol](http://ogp.me/). Per il momento statici e quindi uguali per tutto il sito, poi sistemeremo tutti i meta tags più avanti.
