### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by ranbureand** [alpacaaa/dude#9]
Do we need or do we not need a Google Analytics?

**Comment by alpacaaa** [comment]
A part of me wants to follow the "Fuck Google" route, but I don't have any alternative and it's so convenient...

**Comment by ranbureand** [comment]
There’s [Piwik](http://piwik.org/)! I was using it in the past, but then it got broken during an update and I have never been able to fix it….

**Comment by alpacaaa** [comment]
Yeah I've used it a couple of times... honestly I don't wanna bother with self hosted solutions, we should rely on an external service. I think GA is the way to go.

**Comment by alpacaaa** [comment]
Google Analytics installato, al prossimo pull potresti necessitare di un `npm install` (sempre dentro a `client`).
